version: 2.1

anchors:
  context: &context
    context: slack-notify

  filter_stage: &filter_stage
    filters:
      branches:
        only: ci-test

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  # aws-ecs: circleci/aws-ecs@03.2.0
  slack: circleci/slack@4.12.0

commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

jobs:
  test-config:
    docker:
      - image: cimg/base:2023.02
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt-get update
      - run: echo $CIRCLE_SHA1

workflows:
  build-and-deploy:
    jobs:
      - test-config
      # - aws-ecr/build-and-push-image:
      #     repo: "${AWS_RESOURCE_NAME_PREFIX}"
      #     tag: "${CIRCLE_SHA1}"

# VS Code Extension Version: 1.5.1
